# Generated by Django 6.0.4 on 2026-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('CAR', 'Personal Car'), ('TAXI', 'Taxi'), ('COASTER', 'Coaster'), ('BODA', 'Boda-boda')], max_length=20)),
                ('number_plate', models.CharField(max_length=10)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
