# Generated by Django 6.0.4 on 2026-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='parking_fee',
            field=models.IntegerField(default=0),
        ),
    ]
