# Generated by Django 6.0.4 on 2026-04-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0002_vehicle_parking_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('exit_time', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nin_number', models.CharField(max_length=20)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking_system.vehicle')),
            ],
        ),
    ]
