# Generated by Django 6.0.4 on 2026-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0003_signout'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_parked',
            field=models.BooleanField(default=True),
        ),
    ]
