# Generated by Django 6.0.4 on 2026-04-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0004_vehicle_is_parked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='parking_fee',
        ),
        migrations.AddField(
            model_name='signout',
            name='fee_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
