# Generated by Django 6.0.4 on 2026-04-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0005_remove_vehicle_parking_fee_signout_fee_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('receiver_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('nin_number', models.CharField(max_length=14)),
                ('amount_paid', models.IntegerField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
