# Generated by Django 6.0.4 on 2026-04-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0006_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AlterField(
            model_name='signout',
            name='fee_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signout',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signout',
            name='nin_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='signout',
            name='receipt_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
