# Generated by Django 6.0.4 on 2026-04-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('deposit', models.PositiveIntegerField(default=10000)),
                ('hire_fee', models.PositiveIntegerField(default=15000)),
                ('is_returned', models.BooleanField(default=False)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_section.battery')),
            ],
        ),
    ]
