# Generated by Django 6.0.4 on 2026-04-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_system', '0003_signout'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('pressure', 'Pressure (UGX 500)'), ('puncture', 'Puncture Fixing (UGX 5,000)'), ('valves', 'Valves (UGX 5,000)')], max_length=20)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('attendant_name', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_system.vehicle')),
            ],
        ),
    ]
